name: dino_run
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-140.0.dev <4.0.0'

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Enemies/Bat/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/Rino/
    - assets/images/Backgrounds/
    - assets/audio/
